CREATE SCHEMA IF NOT EXISTS student_portal;
SET search_path TO student_portal;
-- Student Assignment Submission Portal: tables for a hosted MySQL database.
-- (The original student_portal.sql was empty, so this is rebuilt from the columns the PHP code uses.)

CREATE TABLE IF NOT EXISTS students (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_name VARCHAR(100) NOT NULL,
  enrollment_number VARCHAR(50) NOT NULL UNIQUE,
  email VARCHAR(100),
  department VARCHAR(100),
  semester VARCHAR(20),
  password VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS assignments (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  enrollment_number VARCHAR(50),
  student_name VARCHAR(100),
  assignment_title VARCHAR(255),
  assignment_file VARCHAR(255),
  submitted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  -- Added for the faculty side (review / grading)
  marks INT NULL,
  feedback TEXT NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'Submitted',
  reviewed_at TIMESTAMP NULL
);

-- Added for Vercel: sessions and submitted files live in the database
CREATE TABLE IF NOT EXISTS php_sessions (
  id VARCHAR(128) NOT NULL PRIMARY KEY,
  data TEXT NOT NULL,
  expires INT NOT NULL
);

CREATE TABLE IF NOT EXISTS uploaded_files (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  enrollment_number VARCHAR(50),
  filename VARCHAR(255) NOT NULL,
  mime VARCHAR(100),
  data BYTEA NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- =========================================================
-- FACULTY SIDE
-- =========================================================
CREATE TABLE IF NOT EXISTS faculty (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  faculty_name VARCHAR(100) NOT NULL,
  username VARCHAR(50) NOT NULL UNIQUE,
  email VARCHAR(100),
  department VARCHAR(100),
  password VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Assignments created by faculty (the existing `assignments` table holds student submissions)
CREATE TABLE IF NOT EXISTS faculty_assignments (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  faculty_id INT NOT NULL,
  title VARCHAR(255) NOT NULL,
  subject VARCHAR(100),
  description TEXT,
  instructions TEXT,
  department VARCHAR(100) NOT NULL DEFAULT 'All',
  semester VARCHAR(20) NOT NULL DEFAULT 'All',
  due_date DATE NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Default faculty login:  username `faculty`  /  password `faculty123`  (change it after first login)
INSERT INTO faculty (faculty_name, username, email, department, password)
VALUES ('Default Faculty', 'faculty', 'faculty@portal.local', 'CSE',
        '$2y$10$dn8W2il.rbsDlJ4gm75uGu0fgv4TiFhVA8vUqIdgcI6pu59BgPu9e')
ON CONFLICT (username) DO NOTHING;

-- If your database already exists and you do not want to re-run everything, run only this:
-- ALTER TABLE assignments ADD COLUMN marks INT NULL, ADD COLUMN feedback TEXT NULL,
--   ADD COLUMN status VARCHAR(30) NOT NULL DEFAULT 'Submitted', ADD COLUMN reviewed_at TIMESTAMP NULL;
-- (The faculty pages also create the faculty tables / columns automatically if they are missing.)
